### PR TITLE
Add photo, add introduction and modify random messages

### PR DESCRIPTION
**Pull request by Giost**
Add selfie and introduction
Modify random messages to random quote from TV show or a random fact about myself.

### CODE REVIEW

**Comment by dola** [comment]
Your image has a size of ~3 MB which is huge for a website. Even if it's just displayed at a smaller scale it will have to be downloaded fully to display which causes significant increases in load time.

I recommend scaling the image down to 2x or 3x the size at which you're going to display it.

**Comment by Giost** [comment]
Thanks for the advice. I resized the image.

**Review by dola — APPROVED** [review]
looks good!

**Comment by dola** [comment]
There are options to merge:
 - create a merge commit
 - squash and merge
 - rebase and merge

I always prefer either rebase or squash to keep the master branch more linear and free of merge commits. Generally up to you. My way of deciding is usually: 
 - is there only one commit: __use rebase and merge__
 - are there multiple commits?:
   - do they make sense individually and each only add a small feature at a time? Also does the app work at each stage inbetween? -> __Use rebase and merge__
   - are the commits more like steps to reach one bigger goal, potentially the app doesn't even run without errors/bugs after each of them? -> __Use squash and merge__, if possible with a good single commit message describing the whole feature.

**Pull request merged**
